/****************************************************************************
 *
 *   Copyright (C) 2013-2022 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file msg/PrecLandStatus.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus
#define PREC_LAND_STATUS_PREC_LAND_STATE_STOPPED 0
#define PREC_LAND_STATUS_PREC_LAND_STATE_START 1
#define PREC_LAND_STATUS_PREC_LAND_STATE_HORIZONTAL 2
#define PREC_LAND_STATUS_PREC_LAND_STATE_DESCEND 3
#define PREC_LAND_STATUS_PREC_LAND_STATE_FINAL 4
#define PREC_LAND_STATUS_PREC_LAND_STATE_SEARCH 5
#define PREC_LAND_STATUS_PREC_LAND_STATE_FALLBACK 6
#define PREC_LAND_STATUS_PREC_LAND_STATE_DONE 7

#endif


#ifdef __cplusplus
struct __EXPORT prec_land_status_s {
#else
struct prec_land_status_s {
#endif
	uint64_t timestamp;
	uint8_t state;
	uint8_t _padding0[7]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t PREC_LAND_STATE_STOPPED = 0;
	static constexpr uint8_t PREC_LAND_STATE_START = 1;
	static constexpr uint8_t PREC_LAND_STATE_HORIZONTAL = 2;
	static constexpr uint8_t PREC_LAND_STATE_DESCEND = 3;
	static constexpr uint8_t PREC_LAND_STATE_FINAL = 4;
	static constexpr uint8_t PREC_LAND_STATE_SEARCH = 5;
	static constexpr uint8_t PREC_LAND_STATE_FALLBACK = 6;
	static constexpr uint8_t PREC_LAND_STATE_DONE = 7;

#endif
};

#ifdef __cplusplus
namespace px4 {
	namespace msg {
		using PrecLandStatus = prec_land_status_s;
	} // namespace msg
} // namespace px4
#endif

/* register this as object request broker structure */
ORB_DECLARE(prec_land_status);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const prec_land_status_s& message);
#endif

#ifndef __cplusplus  /* P4: C tag->tip (plain-struct ile ayni; C uchus kodu bare-tip kullanir) */
typedef struct prec_land_status_s prec_land_status_s;
#endif
