/****************************************************************************
 *
 *   Copyright (C) 2021-2022 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/


#pragma once

#include <stddef.h>

#include <uORB/uORB.h>

static constexpr size_t ORB_TOPICS_COUNT{327};
static constexpr size_t orb_topics_count() { return ORB_TOPICS_COUNT; }

/*
 * Returns array of topics metadata
 */
extern const struct orb_metadata *const *orb_get_topics() __EXPORT;

enum class ORB_ID : orb_id_size_t {
	action_request = 0,
	actuator_armed = 1,
	actuator_controls_status_0 = 2,
	actuator_controls_status_1 = 3,
	actuator_motors = 4,
	actuator_outputs = 5,
	actuator_outputs_debug = 6,
	actuator_outputs_sim = 7,
	actuator_servos = 8,
	actuator_servos_trim = 9,
	actuator_test = 10,
	adc_report = 11,
	airspeed = 12,
	airspeed_validated = 13,
	airspeed_wind = 14,
	arming_check_reply = 15,
	arming_check_request = 16,
	autotune_attitude_control_status = 17,
	aux_global_position = 18,
	battery_info = 19,
	battery_status = 20,
	button_event = 21,
	camera_capture = 22,
	camera_status = 23,
	camera_trigger = 24,
	can_interface_status = 25,
	cellular_status = 26,
	collision_constraints = 27,
	config_control_setpoints = 28,
	config_overrides = 29,
	config_overrides_request = 30,
	control_allocator_status = 31,
	cpuload = 32,
	dataman_request = 33,
	dataman_response = 34,
	debug_array = 35,
	debug_key_value = 36,
	debug_value = 37,
	debug_vect = 38,
	device_information = 39,
	differential_pressure = 40,
	distance_sensor = 41,
	distance_sensor_mode_change_request = 42,
	dronecan_node_status = 43,
	ekf2_timestamps = 44,
	esc_eeprom_read = 45,
	esc_eeprom_write = 46,
	esc_report = 47,
	esc_serial_passthru = 48,
	esc_status = 49,
	estimator_aid_src_airspeed = 50,
	estimator_aid_src_aux_global_position = 51,
	estimator_aid_src_aux_vel = 52,
	estimator_aid_src_baro_hgt = 53,
	estimator_aid_src_drag = 54,
	estimator_aid_src_ev_hgt = 55,
	estimator_aid_src_ev_pos = 56,
	estimator_aid_src_ev_vel = 57,
	estimator_aid_src_ev_yaw = 58,
	estimator_aid_src_fake_hgt = 59,
	estimator_aid_src_fake_pos = 60,
	estimator_aid_src_gnss_hgt = 61,
	estimator_aid_src_gnss_pos = 62,
	estimator_aid_src_gnss_vel = 63,
	estimator_aid_src_gnss_yaw = 64,
	estimator_aid_src_gravity = 65,
	estimator_aid_src_mag = 66,
	estimator_aid_src_optical_flow = 67,
	estimator_aid_src_ranging_beacon = 68,
	estimator_aid_src_rng_hgt = 69,
	estimator_aid_src_sideslip = 70,
	estimator_attitude = 71,
	estimator_baro_bias = 72,
	estimator_bias3d = 73,
	estimator_ev_pos_bias = 74,
	estimator_event_flags = 75,
	estimator_fusion_control = 76,
	estimator_global_position = 77,
	estimator_gnss_hgt_bias = 78,
	estimator_gps_status = 79,
	estimator_innovation_test_ratios = 80,
	estimator_innovation_variances = 81,
	estimator_innovations = 82,
	estimator_local_position = 83,
	estimator_odometry = 84,
	estimator_optical_flow_vel = 85,
	estimator_selector_status = 86,
	estimator_sensor_bias = 87,
	estimator_states = 88,
	estimator_status = 89,
	estimator_status_flags = 90,
	estimator_wind = 91,
	event = 92,
	external_ins_attitude = 93,
	external_ins_global_position = 94,
	external_ins_local_position = 95,
	failsafe_flags = 96,
	failure_detector_status = 97,
	fiducial_marker_pos_report = 98,
	fiducial_marker_yaw_report = 99,
	figure_eight_status = 100,
	fixed_wing_lateral_guidance_status = 101,
	fixed_wing_lateral_setpoint = 102,
	fixed_wing_lateral_status = 103,
	fixed_wing_longitudinal_setpoint = 104,
	fixed_wing_runway_control = 105,
	flaps_setpoint = 106,
	flight_phase_estimation = 107,
	follow_target = 108,
	follow_target_estimator = 109,
	follow_target_status = 110,
	fuel_tank_status = 111,
	fw_virtual_attitude_setpoint = 112,
	gain_compression = 113,
	generator_status = 114,
	geofence_result = 115,
	geofence_status = 116,
	gimbal_controls = 117,
	gimbal_device_attitude_status = 118,
	gimbal_device_information = 119,
	gimbal_device_set_attitude = 120,
	gimbal_manager_information = 121,
	gimbal_manager_set_attitude = 122,
	gimbal_manager_set_manual_control = 123,
	gimbal_manager_status = 124,
	gimbal_v1_command = 125,
	goto_setpoint = 126,
	gpio_config = 127,
	gpio_in = 128,
	gpio_out = 129,
	gpio_request = 130,
	gps_dump = 131,
	gps_inject_data = 132,
	gripper = 133,
	health_report = 134,
	heater_status = 135,
	home_position = 136,
	hover_thrust_estimate = 137,
	input_rc = 138,
	internal_combustion_engine_control = 139,
	internal_combustion_engine_status = 140,
	io_serial_passthru = 141,
	iridiumsbd_status = 142,
	irlock_report = 143,
	landing_gear = 144,
	landing_gear_wheel = 145,
	landing_target_innovations = 146,
	landing_target_pose = 147,
	lateral_control_configuration = 148,
	launch_detection_status = 149,
	led_control = 150,
	log_message = 151,
	logger_status = 152,
	longitudinal_control_configuration = 153,
	mag_worker_data = 154,
	magnetometer_bias_estimate = 155,
	manual_control_input = 156,
	manual_control_setpoint = 157,
	manual_control_switches = 158,
	mavlink_log = 159,
	mavlink_tunnel = 160,
	mc_virtual_attitude_setpoint = 161,
	message_format_request = 162,
	message_format_response = 163,
	mission = 164,
	mission_result = 165,
	mode_completed = 166,
	mount_orientation = 167,
	navigator_mission_item = 168,
	navigator_status = 169,
	neural_control = 170,
	obstacle_distance = 171,
	obstacle_distance_fused = 172,
	offboard_control_mode = 173,
	onboard_computer_status = 174,
	open_drone_id_arm_status = 175,
	open_drone_id_operator_id = 176,
	open_drone_id_self_id = 177,
	open_drone_id_system = 178,
	orb_multitest = 179,
	orb_test = 180,
	orb_test_large = 181,
	orb_test_medium = 182,
	orb_test_medium_multi = 183,
	orb_test_medium_queue = 184,
	orb_test_medium_queue_poll = 185,
	orb_test_medium_wrap_around = 186,
	orbit_status = 187,
	parameter_primary_set_value_request = 188,
	parameter_primary_set_value_response = 189,
	parameter_remote_set_value_request = 190,
	parameter_remote_set_value_response = 191,
	parameter_reset_request = 192,
	parameter_set_used_request = 193,
	parameter_set_value_request = 194,
	parameter_set_value_response = 195,
	parameter_update = 196,
	ping = 197,
	position_controller_landing_status = 198,
	position_controller_status = 199,
	position_setpoint = 200,
	position_setpoint_triplet = 201,
	power_button_state = 202,
	power_monitor = 203,
	pps_capture = 204,
	prec_land_status = 205,
	pure_pursuit_status = 206,
	pwm_input = 207,
	px4io_status = 208,
	qshell_req = 209,
	qshell_retval = 210,
	radio_status = 211,
	ranging_beacon = 212,
	raptor_input = 213,
	raptor_status = 214,
	rate_ctrl_status = 215,
	rc_channels = 216,
	rc_parameter_map = 217,
	register_ext_component_reply = 218,
	register_ext_component_request = 219,
	rover_attitude_setpoint = 220,
	rover_attitude_status = 221,
	rover_position_setpoint = 222,
	rover_rate_setpoint = 223,
	rover_rate_status = 224,
	rover_speed_setpoint = 225,
	rover_speed_status = 226,
	rover_steering_setpoint = 227,
	rover_throttle_setpoint = 228,
	rpm = 229,
	rtl_status = 230,
	rtl_time_estimate = 231,
	safety_button = 232,
	satellite_info = 233,
	sensor_accel = 234,
	sensor_accel_fifo = 235,
	sensor_airflow = 236,
	sensor_baro = 237,
	sensor_combined = 238,
	sensor_correction = 239,
	sensor_gnss_relative = 240,
	sensor_gnss_status = 241,
	sensor_gps = 242,
	sensor_gyro = 243,
	sensor_gyro_fft = 244,
	sensor_gyro_fifo = 245,
	sensor_hygrometer = 246,
	sensor_mag = 247,
	sensor_optical_flow = 248,
	sensor_preflight_mag = 249,
	sensor_selection = 250,
	sensor_temp = 251,
	sensor_uwb = 252,
	sensors_status_baro = 253,
	sensors_status_imu = 254,
	sensors_status_mag = 255,
	spoilers_setpoint = 256,
	system_power = 257,
	takeoff_status = 258,
	target_gnss = 259,
	task_stack_info = 260,
	tecs_status = 261,
	telemetry_status = 262,
	tiltrotor_extra_controls = 263,
	timesync_status = 264,
	trajectory_setpoint = 265,
	trajectory_setpoint6dof = 266,
	transponder_report = 267,
	tune_control = 268,
	uavcan_parameter_request = 269,
	uavcan_parameter_value = 270,
	ulog_stream = 271,
	ulog_stream_ack = 272,
	unregister_ext_component = 273,
	vehicle_acceleration = 274,
	vehicle_air_data = 275,
	vehicle_angular_acceleration_setpoint = 276,
	vehicle_angular_velocity = 277,
	vehicle_angular_velocity_groundtruth = 278,
	vehicle_attitude = 279,
	vehicle_attitude_groundtruth = 280,
	vehicle_attitude_setpoint = 281,
	vehicle_command = 282,
	vehicle_command_ack = 283,
	vehicle_command_mode_executor = 284,
	vehicle_constraints = 285,
	vehicle_control_mode = 286,
	vehicle_global_position = 287,
	vehicle_global_position_groundtruth = 288,
	vehicle_gps_position = 289,
	vehicle_imu = 290,
	vehicle_imu_status = 291,
	vehicle_land_detected = 292,
	vehicle_local_position = 293,
	vehicle_local_position_groundtruth = 294,
	vehicle_local_position_setpoint = 295,
	vehicle_magnetometer = 296,
	vehicle_mocap_odometry = 297,
	vehicle_odometry = 298,
	vehicle_optical_flow = 299,
	vehicle_optical_flow_vel = 300,
	vehicle_rates_setpoint = 301,
	vehicle_roi = 302,
	vehicle_status = 303,
	vehicle_thrust_setpoint = 304,
	vehicle_thrust_setpoint_virtual_fw = 305,
	vehicle_thrust_setpoint_virtual_mc = 306,
	vehicle_torque_setpoint = 307,
	vehicle_torque_setpoint_virtual_fw = 308,
	vehicle_torque_setpoint_virtual_mc = 309,
	vehicle_visual_odometry = 310,
	velocity_limits = 311,
	vte_aid_ev_yaw = 312,
	vte_aid_fiducial_marker = 313,
	vte_aid_gps_pos_mission = 314,
	vte_aid_gps_pos_target = 315,
	vte_aid_gps_vel_target = 316,
	vte_aid_gps_vel_uav = 317,
	vte_bias_init_status = 318,
	vte_input = 319,
	vte_orientation = 320,
	vte_position = 321,
	vtol_vehicle_status = 322,
	vtx = 323,
	wheel_encoders = 324,
	wind = 325,
	yaw_estimator_status = 326,

	INVALID
};

const struct orb_metadata *get_orb_meta(ORB_ID id);
