/****************************************************************************
 *
 *   Copyright (C) 2013-2022 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file msg/VteAidSource3d.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus
#define VTE_AID_SOURCE3D_STATUS_IDLE 0
#define VTE_AID_SOURCE3D_STATUS_FUSED_CURRENT 1
#define VTE_AID_SOURCE3D_STATUS_FUSED_OOSM 2
#define VTE_AID_SOURCE3D_STATUS_REJECT_NIS 3
#define VTE_AID_SOURCE3D_STATUS_REJECT_COV 4
#define VTE_AID_SOURCE3D_STATUS_REJECT_TOO_OLD 5
#define VTE_AID_SOURCE3D_STATUS_REJECT_TOO_NEW 6
#define VTE_AID_SOURCE3D_STATUS_REJECT_STALE 7
#define VTE_AID_SOURCE3D_STATUS_REJECT_EMPTY 8

#endif


#ifdef __cplusplus
struct __EXPORT vte_aid_source3d_s {
#else
struct vte_aid_source3d_s {
#endif
	uint64_t timestamp;
	uint64_t timestamp_sample;
	uint64_t time_last_predict;
	float observation[3];
	float observation_variance[3];
	float innovation[3];
	float innovation_variance[3];
	float test_ratio[3];
	float time_since_meas_ms;
	uint8_t fusion_status[3];
	uint8_t history_steps;
	uint8_t _padding0[4]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t STATUS_IDLE = 0;
	static constexpr uint8_t STATUS_FUSED_CURRENT = 1;
	static constexpr uint8_t STATUS_FUSED_OOSM = 2;
	static constexpr uint8_t STATUS_REJECT_NIS = 3;
	static constexpr uint8_t STATUS_REJECT_COV = 4;
	static constexpr uint8_t STATUS_REJECT_TOO_OLD = 5;
	static constexpr uint8_t STATUS_REJECT_TOO_NEW = 6;
	static constexpr uint8_t STATUS_REJECT_STALE = 7;
	static constexpr uint8_t STATUS_REJECT_EMPTY = 8;

#endif
};

#ifdef __cplusplus
namespace px4 {
	namespace msg {
		using VteAidSource3d = vte_aid_source3d_s;
	} // namespace msg
} // namespace px4
#endif

/* register this as object request broker structure */
ORB_DECLARE(vte_aid_gps_pos_target);
ORB_DECLARE(vte_aid_gps_pos_mission);
ORB_DECLARE(vte_aid_gps_vel_target);
ORB_DECLARE(vte_aid_gps_vel_uav);
ORB_DECLARE(vte_aid_fiducial_marker);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const vte_aid_source3d_s& message);
#endif

#ifndef __cplusplus  /* P4: C tag->tip (plain-struct ile ayni; C uchus kodu bare-tip kullanir) */
typedef struct vte_aid_source3d_s vte_aid_source3d_s;
#endif
